In [5]:
import pandas as pd
import numpy as np

In [4]:
#initialise the 'df' variable with the '.csv' file
df = pd.read_csv("ODI_Match_Results.csv")

In [3]:
#print the first 5 rows
df.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,NaN,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,NaN,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,NaN,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,NaN,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,NaN,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [4]:
#print the first 5 rows
df.tail()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
1317,997,won,3 wickets,3.0,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,NaN,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,NaN,NaN,NaN,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,NaN,NaN,NaN,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,NaN,NaN,NaN,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [5]:
#check for each column the number of NaN's
df.isna().sum()

sl_no           0
Result          3
Margin         96
BR            716
Toss           26
Bat            30
Opposition      0
Ground          0
Start Date      0
Match_ID        0
Country         0
Country_ID      0
dtype: int64

In [6]:
#to find dimensions of the dataset
df.shape

(1322, 12)

In [7]:
df.isnull().mean()

sl_no         0.000000
Result        0.002269
Margin        0.072617
BR            0.541604
Toss          0.019667
Bat           0.022693
Opposition    0.000000
Ground        0.000000
Start Date    0.000000
Match_ID      0.000000
Country       0.000000
Country_ID    0.000000
dtype: float64

In [8]:
df.isnull().mean().sum()

0.6588502269288956

In [9]:
df.isna().mean()

sl_no         0.000000
Result        0.002269
Margin        0.072617
BR            0.541604
Toss          0.019667
Bat           0.022693
Opposition    0.000000
Ground        0.000000
Start Date    0.000000
Match_ID      0.000000
Country       0.000000
Country_ID    0.000000
dtype: float64

In [10]:
df.isna().mean().sum()

0.6588502269288956

In [11]:
df.isna().sum()

sl_no           0
Result          3
Margin         96
BR            716
Toss           26
Bat            30
Opposition      0
Ground          0
Start Date      0
Match_ID        0
Country         0
Country_ID      0
dtype: int64

In [12]:
df.isna().sum().sum()

871

In [13]:
df.isnull().sum()

sl_no           0
Result          3
Margin         96
BR            716
Toss           26
Bat            30
Opposition      0
Ground          0
Start Date      0
Match_ID        0
Country         0
Country_ID      0
dtype: int64

In [14]:
df.isnull().sum().sum()

871

In [15]:
df.fillna(df.mean())

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8
5,1096,won,107 runs,51.409241,won,1st,v Sri Lanka,Melbourne,11-Jan-13,ODI # 3317,Australia,2
6,694,lost,9 runs,51.409241,lost,2nd,v England,Rajkot,11-Jan-13,ODI # 3318,India,6
7,852,won,9 runs,51.409241,won,1st,v India,Rajkot,11-Jan-13,ODI # 3318,England,1
8,122,won,8 wickets,59.000000,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8
9,1097,lost,8 wickets,59.000000,lost,1st,v Sri Lanka,Adelaide,13-Jan-13,ODI # 3319,Australia,2
10,695,won,127 runs,51.409241,won,1st,v England,Kochi,15-Jan-13,ODI # 3320,India,6
11,853,lost,127 runs,51.409241,lost,2nd,v India,Kochi,15-Jan-13,ODI # 3320,England,1
12,123,won,4 wickets,180.000000,lost,2nd,v Australia,Brisbane,18-Jan-13,ODI # 3321,SriLanka,8
13,1098,lost,4 wickets,180.000000,won,1st,v Sri Lanka,Brisbane,18-Jan-13,ODI # 3321,Australia,2
14,696,won,7 wickets,131.000000,won,2nd,v England,Ranchi,19-Jan-13,ODI # 3322,India,6
15,854,lost,7 wickets,131.000000,lost,1st,v India,Ranchi,19-Jan-13,ODI # 3322,England,1
16,283,lost,1 wickets,26.000000,lost,1st,v New Zealand,Paarl,19-Jan-13,ODI # 3323,SouthAfrica,3
17,560,won,1 wickets,26.000000,won,2nd,v South Africa,Paarl,19-Jan-13,ODI # 3323,NewZealand,5
18,124,n/r,NaN,51.409241,lost,2nd,v Australia,Sydney,20-Jan-13,ODI # 3324,SriLanka,8
19,1099,n/r,NaN,51.409241,won,1st,v Sri Lanka,Sydney,20-Jan-13,ODI # 3324,Australia,2
20,284,lost,27 runs,51.409241,won,2nd,v New Zealand,Kimberley,22-Jan-13,ODI # 3325,SouthAfrica,3
21,561,won,27 runs,51.409241,lost,1st,v South Africa,Kimberley,22-Jan-13,ODI # 3325,NewZealand,5
22,125,lost,32 runs,51.409241,won,2nd,v Australia,Hobart,23-Jan-13,ODI # 3326,SriLanka,8
23,1100,won,32 runs,51.409241,lost,1st,v Sri Lanka,Hobart,23-Jan-13,ODI # 3326,Australia,2
24,697,won,5 wickets,15.000000,won,2nd,v England,Mohali,23-Jan-13,ODI # 3327,India,6
25,855,lost,5 wickets,15.000000,lost,1st,v India,Mohali,23-Jan-13,ODI # 3327,England,1
26,285,won,1 wickets,0.000000,lost,2nd,v New Zealand,Potchefstroom,25-Jan-13,ODI # 3328,SouthAfrica,3
27,562,lost,1 wickets,0.000000,won,1st,v South Africa,Potchefstroom,25-Jan-13,ODI # 3328,NewZealand,5
28,698,lost,7 wickets,16.000000,lost,1st,v England,Dharamsala,27-Jan-13,ODI # 3329,India,6
29,856,won,7 wickets,16.000000,won,2nd,v India,Dharamsala,27-Jan-13,ODI # 3329,England,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1292,1228,won,80 runs,51.409241,won,1st,v Pakistan,Abu Dhabi,27-Mar-19,ODI # 4118,Australia,2
1293,553,lost,6 runs,51.409241,won,2nd,v Australia,Dubai (DSC),29-Mar-19,ODI # 4119,Pakistan,7
1294,1229,won,6 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),29-Mar-19,ODI # 4119,Australia,2
1295,554,lost,20 runs,51.409241,won,2nd,v Australia,Dubai (DSC),31-Mar-19,ODI # 4120,Pakistan,7
1296,1230,won,20 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),31-Mar-19,ODI # 4120,Australia,2
1297,993,won,4 wickets,18.000000,won,2nd,v Ireland,Dublin (Malahide),3-May-19,ODI # 4127,England,1
1298,116,won,196 runs,51.409241,lost,1st,v Ireland,Dublin,5-May-19,ODI # 4128,WestIndies,4
1299,117,lost,8 wickets,30.000000,won,1st,v Bangladesh,Dublin,7-May-19,ODI # 4129,WestIndies,4
1300,1091,won,8 wickets,30.000000,lost,2nd,v West Indies,Dublin,7-May-19,ODI # 4129,Bangladesh,25
1301,1320,aban,NaN,51.409241,NaN,NaN,v Scotland,Edinburgh,8-May-19,ODI # 4129a,Afghanistan,40
1302,555,n/r,NaN,51.409241,lost,1st,v England,The Oval,8-May-19,ODI # 4130,Pakistan,7
1303,994,n/r,NaN,51.409241,won,2nd,v Pakistan,The Oval,8-May-19,ODI # 4130,England,1
1304,1092,aban,NaN,51.409241,NaN,NaN,v Ireland,Dublin (Malahide),9-May-19,ODI # 4130a,Bangladesh,25
1305,1321,won,2 runs,51.409241,lost,2nd,v Scotland,Edinburgh,10-May-19,ODI # 4131,Afghanistan,40
1306,118,won,5 wickets,13.000000,lost,2nd,v Ireland,Dublin (Malahide),11-May-19,ODI # 4132,WestIndies,4
1307,556,lost,12 runs,51.409241,won,2nd,v England,Southampton,11-May-19,ODI # 4133,Pakistan,7
1308,995,won,12 runs,51.409241,lost,1st,v Pakistan,Southampton,11-May-19,ODI # 4133,England,1
1309,119,lost,5 wickets,16.000000,won,1st,v Bangladesh,Dublin (Malahide),13-May-19,ODI # 4134,WestIndies,4
1310,1093,won,5 wickets,16.000000,lost,2nd,v West Indies,Dublin (Malahide),13-May-19,ODI # 4134,Bangladesh,25
1311,557,lost,6 wickets,31.000000,lost,1st,v England,Bristol,14-May-19,ODI # 4135,Pakistan,7
1312,996,won,6 wickets,31.000000,won,2nd,v Pakistan,Bristol,14-May-19,ODI # 4135,England,1
1313,1094,won,6 wickets,42.000000,lost,2nd,v Ireland,Dublin,15-May-19,ODI # 4136,Bangladesh,25
1314,120,lost,5 wickets,7.000000,lost,1st,v Bangladesh,Dublin (Malahide),17-May-19,ODI # 4137,WestIndies,4
1315,1095,won,5 wickets,7.000000,won,2nd,v West Indies,Dublin (Malahide),17-May-19,ODI # 4137,Bangladesh,25
1316,558,lost,3 wickets,3.000000,lost,1st,v England,Nottingham,17-May-19,ODI # 4138,Pakistan,7
1317,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,51.409241,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,NaN,NaN,51.409241,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,NaN,NaN,51.409241,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,NaN,NaN,51.409241,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [16]:
df['BR'].isna().sum()

716

In [17]:
df.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,NaN,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,NaN,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,NaN,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,NaN,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,NaN,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [18]:
df.tail()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
1317,997,won,3 wickets,3.0,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,NaN,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,NaN,NaN,NaN,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,NaN,NaN,NaN,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,NaN,NaN,NaN,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [19]:
df_rem_nan_catego = df.fillna(df.mean())

In [20]:
df_rem_nan_catego

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8
5,1096,won,107 runs,51.409241,won,1st,v Sri Lanka,Melbourne,11-Jan-13,ODI # 3317,Australia,2
6,694,lost,9 runs,51.409241,lost,2nd,v England,Rajkot,11-Jan-13,ODI # 3318,India,6
7,852,won,9 runs,51.409241,won,1st,v India,Rajkot,11-Jan-13,ODI # 3318,England,1
8,122,won,8 wickets,59.000000,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8
9,1097,lost,8 wickets,59.000000,lost,1st,v Sri Lanka,Adelaide,13-Jan-13,ODI # 3319,Australia,2
10,695,won,127 runs,51.409241,won,1st,v England,Kochi,15-Jan-13,ODI # 3320,India,6
11,853,lost,127 runs,51.409241,lost,2nd,v India,Kochi,15-Jan-13,ODI # 3320,England,1
12,123,won,4 wickets,180.000000,lost,2nd,v Australia,Brisbane,18-Jan-13,ODI # 3321,SriLanka,8
13,1098,lost,4 wickets,180.000000,won,1st,v Sri Lanka,Brisbane,18-Jan-13,ODI # 3321,Australia,2
14,696,won,7 wickets,131.000000,won,2nd,v England,Ranchi,19-Jan-13,ODI # 3322,India,6
15,854,lost,7 wickets,131.000000,lost,1st,v India,Ranchi,19-Jan-13,ODI # 3322,England,1
16,283,lost,1 wickets,26.000000,lost,1st,v New Zealand,Paarl,19-Jan-13,ODI # 3323,SouthAfrica,3
17,560,won,1 wickets,26.000000,won,2nd,v South Africa,Paarl,19-Jan-13,ODI # 3323,NewZealand,5
18,124,n/r,NaN,51.409241,lost,2nd,v Australia,Sydney,20-Jan-13,ODI # 3324,SriLanka,8
19,1099,n/r,NaN,51.409241,won,1st,v Sri Lanka,Sydney,20-Jan-13,ODI # 3324,Australia,2
20,284,lost,27 runs,51.409241,won,2nd,v New Zealand,Kimberley,22-Jan-13,ODI # 3325,SouthAfrica,3
21,561,won,27 runs,51.409241,lost,1st,v South Africa,Kimberley,22-Jan-13,ODI # 3325,NewZealand,5
22,125,lost,32 runs,51.409241,won,2nd,v Australia,Hobart,23-Jan-13,ODI # 3326,SriLanka,8
23,1100,won,32 runs,51.409241,lost,1st,v Sri Lanka,Hobart,23-Jan-13,ODI # 3326,Australia,2
24,697,won,5 wickets,15.000000,won,2nd,v England,Mohali,23-Jan-13,ODI # 3327,India,6
25,855,lost,5 wickets,15.000000,lost,1st,v India,Mohali,23-Jan-13,ODI # 3327,England,1
26,285,won,1 wickets,0.000000,lost,2nd,v New Zealand,Potchefstroom,25-Jan-13,ODI # 3328,SouthAfrica,3
27,562,lost,1 wickets,0.000000,won,1st,v South Africa,Potchefstroom,25-Jan-13,ODI # 3328,NewZealand,5
28,698,lost,7 wickets,16.000000,lost,1st,v England,Dharamsala,27-Jan-13,ODI # 3329,India,6
29,856,won,7 wickets,16.000000,won,2nd,v India,Dharamsala,27-Jan-13,ODI # 3329,England,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1292,1228,won,80 runs,51.409241,won,1st,v Pakistan,Abu Dhabi,27-Mar-19,ODI # 4118,Australia,2
1293,553,lost,6 runs,51.409241,won,2nd,v Australia,Dubai (DSC),29-Mar-19,ODI # 4119,Pakistan,7
1294,1229,won,6 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),29-Mar-19,ODI # 4119,Australia,2
1295,554,lost,20 runs,51.409241,won,2nd,v Australia,Dubai (DSC),31-Mar-19,ODI # 4120,Pakistan,7
1296,1230,won,20 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),31-Mar-19,ODI # 4120,Australia,2
1297,993,won,4 wickets,18.000000,won,2nd,v Ireland,Dublin (Malahide),3-May-19,ODI # 4127,England,1
1298,116,won,196 runs,51.409241,lost,1st,v Ireland,Dublin,5-May-19,ODI # 4128,WestIndies,4
1299,117,lost,8 wickets,30.000000,won,1st,v Bangladesh,Dublin,7-May-19,ODI # 4129,WestIndies,4
1300,1091,won,8 wickets,30.000000,lost,2nd,v West Indies,Dublin,7-May-19,ODI # 4129,Bangladesh,25
1301,1320,aban,NaN,51.409241,NaN,NaN,v Scotland,Edinburgh,8-May-19,ODI # 4129a,Afghanistan,40
1302,555,n/r,NaN,51.409241,lost,1st,v England,The Oval,8-May-19,ODI # 4130,Pakistan,7
1303,994,n/r,NaN,51.409241,won,2nd,v Pakistan,The Oval,8-May-19,ODI # 4130,England,1
1304,1092,aban,NaN,51.409241,NaN,NaN,v Ireland,Dublin (Malahide),9-May-19,ODI # 4130a,Bangladesh,25
1305,1321,won,2 runs,51.409241,lost,2nd,v Scotland,Edinburgh,10-May-19,ODI # 4131,Afghanistan,40
1306,118,won,5 wickets,13.000000,lost,2nd,v Ireland,Dublin (Malahide),11-May-19,ODI # 4132,WestIndies,4
1307,556,lost,12 runs,51.409241,won,2nd,v England,Southampton,11-May-19,ODI # 4133,Pakistan,7
1308,995,won,12 runs,51.409241,lost,1st,v Pakistan,Southampton,11-May-19,ODI # 4133,England,1
1309,119,lost,5 wickets,16.000000,won,1st,v Bangladesh,Dublin (Malahide),13-May-19,ODI # 4134,WestIndies,4
1310,1093,won,5 wickets,16.000000,lost,2nd,v West Indies,Dublin (Malahide),13-May-19,ODI # 4134,Bangladesh,25
1311,557,lost,6 wickets,31.000000,lost,1st,v England,Bristol,14-May-19,ODI # 4135,Pakistan,7
1312,996,won,6 wickets,31.000000,won,2nd,v Pakistan,Bristol,14-May-19,ODI # 4135,England,1
1313,1094,won,6 wickets,42.000000,lost,2nd,v Ireland,Dublin,15-May-19,ODI # 4136,Bangladesh,25
1314,120,lost,5 wickets,7.000000,lost,1st,v Bangladesh,Dublin (Malahide),17-May-19,ODI # 4137,WestIndies,4
1315,1095,won,5 wickets,7.000000,won,2nd,v West Indies,Dublin (Malahide),17-May-19,ODI # 4137,Bangladesh,25
1316,558,lost,3 wickets,3.000000,lost,1st,v England,Nottingham,17-May-19,ODI # 4138,Pakistan,7
1317,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,51.409241,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,NaN,NaN,51.409241,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,NaN,NaN,51.409241,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,NaN,NaN,51.409241,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [21]:
df_rem_nan_catego.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [22]:
df_rem_nan_catego.tail()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
1317,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,51.409241,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,NaN,NaN,51.409241,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,NaN,NaN,51.409241,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,NaN,NaN,51.409241,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [23]:
df["Result"].fillna( method ='ffill', inplace = True)

In [24]:
df.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,NaN,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,NaN,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,NaN,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,NaN,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,NaN,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [25]:
df.tail()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
1317,997,won,3 wickets,3.0,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,NaN,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,aban,NaN,NaN,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,aban,NaN,NaN,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,aban,NaN,NaN,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [26]:
df['BR'].fillna(df.mean())

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8        59.0
9        59.0
10        NaN
11        NaN
12      180.0
13      180.0
14      131.0
15      131.0
16       26.0
17       26.0
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24       15.0
25       15.0
26        0.0
27        0.0
28       16.0
29       16.0
        ...
1292      NaN
1293      NaN
1294      NaN
1295      NaN
1296      NaN
1297     18.0
1298      NaN
1299     30.0
1300     30.0
1301      NaN
1302      NaN
1303      NaN
1304      NaN
1305      NaN
1306     13.0
1307      NaN
1308      NaN
1309     16.0
1310     16.0
1311     31.0
1312     31.0
1313     42.0
1314      7.0
1315      7.0
1316      3.0
1317      3.0
1318      NaN
1319      NaN
1320      NaN
1321      NaN
Name: BR, Length: 1322, dtype: float64

In [27]:
df.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,NaN,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,NaN,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,NaN,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,NaN,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,NaN,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [28]:
df.tail()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
1317,997,won,3 wickets,3.0,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,NaN,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,aban,NaN,NaN,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,aban,NaN,NaN,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,aban,NaN,NaN,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [29]:
df.fillna(df.mean())

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8
5,1096,won,107 runs,51.409241,won,1st,v Sri Lanka,Melbourne,11-Jan-13,ODI # 3317,Australia,2
6,694,lost,9 runs,51.409241,lost,2nd,v England,Rajkot,11-Jan-13,ODI # 3318,India,6
7,852,won,9 runs,51.409241,won,1st,v India,Rajkot,11-Jan-13,ODI # 3318,England,1
8,122,won,8 wickets,59.000000,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8
9,1097,lost,8 wickets,59.000000,lost,1st,v Sri Lanka,Adelaide,13-Jan-13,ODI # 3319,Australia,2
10,695,won,127 runs,51.409241,won,1st,v England,Kochi,15-Jan-13,ODI # 3320,India,6
11,853,lost,127 runs,51.409241,lost,2nd,v India,Kochi,15-Jan-13,ODI # 3320,England,1
12,123,won,4 wickets,180.000000,lost,2nd,v Australia,Brisbane,18-Jan-13,ODI # 3321,SriLanka,8
13,1098,lost,4 wickets,180.000000,won,1st,v Sri Lanka,Brisbane,18-Jan-13,ODI # 3321,Australia,2
14,696,won,7 wickets,131.000000,won,2nd,v England,Ranchi,19-Jan-13,ODI # 3322,India,6
15,854,lost,7 wickets,131.000000,lost,1st,v India,Ranchi,19-Jan-13,ODI # 3322,England,1
16,283,lost,1 wickets,26.000000,lost,1st,v New Zealand,Paarl,19-Jan-13,ODI # 3323,SouthAfrica,3
17,560,won,1 wickets,26.000000,won,2nd,v South Africa,Paarl,19-Jan-13,ODI # 3323,NewZealand,5
18,124,n/r,NaN,51.409241,lost,2nd,v Australia,Sydney,20-Jan-13,ODI # 3324,SriLanka,8
19,1099,n/r,NaN,51.409241,won,1st,v Sri Lanka,Sydney,20-Jan-13,ODI # 3324,Australia,2
20,284,lost,27 runs,51.409241,won,2nd,v New Zealand,Kimberley,22-Jan-13,ODI # 3325,SouthAfrica,3
21,561,won,27 runs,51.409241,lost,1st,v South Africa,Kimberley,22-Jan-13,ODI # 3325,NewZealand,5
22,125,lost,32 runs,51.409241,won,2nd,v Australia,Hobart,23-Jan-13,ODI # 3326,SriLanka,8
23,1100,won,32 runs,51.409241,lost,1st,v Sri Lanka,Hobart,23-Jan-13,ODI # 3326,Australia,2
24,697,won,5 wickets,15.000000,won,2nd,v England,Mohali,23-Jan-13,ODI # 3327,India,6
25,855,lost,5 wickets,15.000000,lost,1st,v India,Mohali,23-Jan-13,ODI # 3327,England,1
26,285,won,1 wickets,0.000000,lost,2nd,v New Zealand,Potchefstroom,25-Jan-13,ODI # 3328,SouthAfrica,3
27,562,lost,1 wickets,0.000000,won,1st,v South Africa,Potchefstroom,25-Jan-13,ODI # 3328,NewZealand,5
28,698,lost,7 wickets,16.000000,lost,1st,v England,Dharamsala,27-Jan-13,ODI # 3329,India,6
29,856,won,7 wickets,16.000000,won,2nd,v India,Dharamsala,27-Jan-13,ODI # 3329,England,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1292,1228,won,80 runs,51.409241,won,1st,v Pakistan,Abu Dhabi,27-Mar-19,ODI # 4118,Australia,2
1293,553,lost,6 runs,51.409241,won,2nd,v Australia,Dubai (DSC),29-Mar-19,ODI # 4119,Pakistan,7
1294,1229,won,6 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),29-Mar-19,ODI # 4119,Australia,2
1295,554,lost,20 runs,51.409241,won,2nd,v Australia,Dubai (DSC),31-Mar-19,ODI # 4120,Pakistan,7
1296,1230,won,20 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),31-Mar-19,ODI # 4120,Australia,2
1297,993,won,4 wickets,18.000000,won,2nd,v Ireland,Dublin (Malahide),3-May-19,ODI # 4127,England,1
1298,116,won,196 runs,51.409241,lost,1st,v Ireland,Dublin,5-May-19,ODI # 4128,WestIndies,4
1299,117,lost,8 wickets,30.000000,won,1st,v Bangladesh,Dublin,7-May-19,ODI # 4129,WestIndies,4
1300,1091,won,8 wickets,30.000000,lost,2nd,v West Indies,Dublin,7-May-19,ODI # 4129,Bangladesh,25
1301,1320,aban,NaN,51.409241,NaN,NaN,v Scotland,Edinburgh,8-May-19,ODI # 4129a,Afghanistan,40
1302,555,n/r,NaN,51.409241,lost,1st,v England,The Oval,8-May-19,ODI # 4130,Pakistan,7
1303,994,n/r,NaN,51.409241,won,2nd,v Pakistan,The Oval,8-May-19,ODI # 4130,England,1
1304,1092,aban,NaN,51.409241,NaN,NaN,v Ireland,Dublin (Malahide),9-May-19,ODI # 4130a,Bangladesh,25
1305,1321,won,2 runs,51.409241,lost,2nd,v Scotland,Edinburgh,10-May-19,ODI # 4131,Afghanistan,40
1306,118,won,5 wickets,13.000000,lost,2nd,v Ireland,Dublin (Malahide),11-May-19,ODI # 4132,WestIndies,4
1307,556,lost,12 runs,51.409241,won,2nd,v England,Southampton,11-May-19,ODI # 4133,Pakistan,7
1308,995,won,12 runs,51.409241,lost,1st,v Pakistan,Southampton,11-May-19,ODI # 4133,England,1
1309,119,lost,5 wickets,16.000000,won,1st,v Bangladesh,Dublin (Malahide),13-May-19,ODI # 4134,WestIndies,4
1310,1093,won,5 wickets,16.000000,lost,2nd,v West Indies,Dublin (Malahide),13-May-19,ODI # 4134,Bangladesh,25
1311,557,lost,6 wickets,31.000000,lost,1st,v England,Bristol,14-May-19,ODI # 4135,Pakistan,7
1312,996,won,6 wickets,31.000000,won,2nd,v Pakistan,Bristol,14-May-19,ODI # 4135,England,1
1313,1094,won,6 wickets,42.000000,lost,2nd,v Ireland,Dublin,15-May-19,ODI # 4136,Bangladesh,25
1314,120,lost,5 wickets,7.000000,lost,1st,v Bangladesh,Dublin (Malahide),17-May-19,ODI # 4137,WestIndies,4
1315,1095,won,5 wickets,7.000000,won,2nd,v West Indies,Dublin (Malahide),17-May-19,ODI # 4137,Bangladesh,25
1316,558,lost,3 wickets,3.000000,lost,1st,v England,Nottingham,17-May-19,ODI # 4138,Pakistan,7
1317,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,51.409241,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,aban,NaN,51.409241,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,aban,NaN,51.409241,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,aban,NaN,51.409241,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [30]:
df['BR'].fillna(df['BR'].mean())

0        51.409241
1        51.409241
2        51.409241
3        51.409241
4        51.409241
5        51.409241
6        51.409241
7        51.409241
8        59.000000
9        59.000000
10       51.409241
11       51.409241
12      180.000000
13      180.000000
14      131.000000
15      131.000000
16       26.000000
17       26.000000
18       51.409241
19       51.409241
20       51.409241
21       51.409241
22       51.409241
23       51.409241
24       15.000000
25       15.000000
26        0.000000
27        0.000000
28       16.000000
29       16.000000
           ...
1292     51.409241
1293     51.409241
1294     51.409241
1295     51.409241
1296     51.409241
1297     18.000000
1298     51.409241
1299     30.000000
1300     30.000000
1301     51.409241
1302     51.409241
1303     51.409241
1304     51.409241
1305     51.409241
1306     13.000000
1307     51.409241
1308     51.409241
1309     16.000000
1310     16.000000
1311     31.000000
1312     31.000000
1313     42.000000
1314      7.000000
1315      7.000000
1316      3.000000
1317      3.000000
1318     51.409241
1319     51.409241
1320     51.409241
1321     51.409241
Name: BR, Length: 1322, dtype: float64

In [31]:
df.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,NaN,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,NaN,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,NaN,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,NaN,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,NaN,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [32]:
df['BR'].fillna(df['BR'].mean(), inplace = True)

In [33]:
df.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [34]:
df["Margin"].fillna( method ='ffill', inplace = True)

In [35]:
df["Toss"].fillna( method ='ffill', inplace = True)

In [36]:
df["Bat"].fillna( method ='ffill', inplace = True)

In [37]:
df.tail()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
1317,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,3 wickets,51.409241,won,2nd,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,aban,3 wickets,51.409241,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,aban,3 wickets,51.409241,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,aban,3 wickets,51.409241,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [38]:
df.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [39]:
df

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8
5,1096,won,107 runs,51.409241,won,1st,v Sri Lanka,Melbourne,11-Jan-13,ODI # 3317,Australia,2
6,694,lost,9 runs,51.409241,lost,2nd,v England,Rajkot,11-Jan-13,ODI # 3318,India,6
7,852,won,9 runs,51.409241,won,1st,v India,Rajkot,11-Jan-13,ODI # 3318,England,1
8,122,won,8 wickets,59.000000,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8
9,1097,lost,8 wickets,59.000000,lost,1st,v Sri Lanka,Adelaide,13-Jan-13,ODI # 3319,Australia,2
10,695,won,127 runs,51.409241,won,1st,v England,Kochi,15-Jan-13,ODI # 3320,India,6
11,853,lost,127 runs,51.409241,lost,2nd,v India,Kochi,15-Jan-13,ODI # 3320,England,1
12,123,won,4 wickets,180.000000,lost,2nd,v Australia,Brisbane,18-Jan-13,ODI # 3321,SriLanka,8
13,1098,lost,4 wickets,180.000000,won,1st,v Sri Lanka,Brisbane,18-Jan-13,ODI # 3321,Australia,2
14,696,won,7 wickets,131.000000,won,2nd,v England,Ranchi,19-Jan-13,ODI # 3322,India,6
15,854,lost,7 wickets,131.000000,lost,1st,v India,Ranchi,19-Jan-13,ODI # 3322,England,1
16,283,lost,1 wickets,26.000000,lost,1st,v New Zealand,Paarl,19-Jan-13,ODI # 3323,SouthAfrica,3
17,560,won,1 wickets,26.000000,won,2nd,v South Africa,Paarl,19-Jan-13,ODI # 3323,NewZealand,5
18,124,n/r,1 wickets,51.409241,lost,2nd,v Australia,Sydney,20-Jan-13,ODI # 3324,SriLanka,8
19,1099,n/r,1 wickets,51.409241,won,1st,v Sri Lanka,Sydney,20-Jan-13,ODI # 3324,Australia,2
20,284,lost,27 runs,51.409241,won,2nd,v New Zealand,Kimberley,22-Jan-13,ODI # 3325,SouthAfrica,3
21,561,won,27 runs,51.409241,lost,1st,v South Africa,Kimberley,22-Jan-13,ODI # 3325,NewZealand,5
22,125,lost,32 runs,51.409241,won,2nd,v Australia,Hobart,23-Jan-13,ODI # 3326,SriLanka,8
23,1100,won,32 runs,51.409241,lost,1st,v Sri Lanka,Hobart,23-Jan-13,ODI # 3326,Australia,2
24,697,won,5 wickets,15.000000,won,2nd,v England,Mohali,23-Jan-13,ODI # 3327,India,6
25,855,lost,5 wickets,15.000000,lost,1st,v India,Mohali,23-Jan-13,ODI # 3327,England,1
26,285,won,1 wickets,0.000000,lost,2nd,v New Zealand,Potchefstroom,25-Jan-13,ODI # 3328,SouthAfrica,3
27,562,lost,1 wickets,0.000000,won,1st,v South Africa,Potchefstroom,25-Jan-13,ODI # 3328,NewZealand,5
28,698,lost,7 wickets,16.000000,lost,1st,v England,Dharamsala,27-Jan-13,ODI # 3329,India,6
29,856,won,7 wickets,16.000000,won,2nd,v India,Dharamsala,27-Jan-13,ODI # 3329,England,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1292,1228,won,80 runs,51.409241,won,1st,v Pakistan,Abu Dhabi,27-Mar-19,ODI # 4118,Australia,2
1293,553,lost,6 runs,51.409241,won,2nd,v Australia,Dubai (DSC),29-Mar-19,ODI # 4119,Pakistan,7
1294,1229,won,6 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),29-Mar-19,ODI # 4119,Australia,2
1295,554,lost,20 runs,51.409241,won,2nd,v Australia,Dubai (DSC),31-Mar-19,ODI # 4120,Pakistan,7
1296,1230,won,20 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),31-Mar-19,ODI # 4120,Australia,2
1297,993,won,4 wickets,18.000000,won,2nd,v Ireland,Dublin (Malahide),3-May-19,ODI # 4127,England,1
1298,116,won,196 runs,51.409241,lost,1st,v Ireland,Dublin,5-May-19,ODI # 4128,WestIndies,4
1299,117,lost,8 wickets,30.000000,won,1st,v Bangladesh,Dublin,7-May-19,ODI # 4129,WestIndies,4
1300,1091,won,8 wickets,30.000000,lost,2nd,v West Indies,Dublin,7-May-19,ODI # 4129,Bangladesh,25
1301,1320,aban,8 wickets,51.409241,lost,2nd,v Scotland,Edinburgh,8-May-19,ODI # 4129a,Afghanistan,40
1302,555,n/r,8 wickets,51.409241,lost,1st,v England,The Oval,8-May-19,ODI # 4130,Pakistan,7
1303,994,n/r,8 wickets,51.409241,won,2nd,v Pakistan,The Oval,8-May-19,ODI # 4130,England,1
1304,1092,aban,8 wickets,51.409241,won,2nd,v Ireland,Dublin (Malahide),9-May-19,ODI # 4130a,Bangladesh,25
1305,1321,won,2 runs,51.409241,lost,2nd,v Scotland,Edinburgh,10-May-19,ODI # 4131,Afghanistan,40
1306,118,won,5 wickets,13.000000,lost,2nd,v Ireland,Dublin (Malahide),11-May-19,ODI # 4132,WestIndies,4
1307,556,lost,12 runs,51.409241,won,2nd,v England,Southampton,11-May-19,ODI # 4133,Pakistan,7
1308,995,won,12 runs,51.409241,lost,1st,v Pakistan,Southampton,11-May-19,ODI # 4133,England,1
1309,119,lost,5 wickets,16.000000,won,1st,v Bangladesh,Dublin (Malahide),13-May-19,ODI # 4134,WestIndies,4
1310,1093,won,5 wickets,16.000000,lost,2nd,v West Indies,Dublin (Malahide),13-May-19,ODI # 4134,Bangladesh,25
1311,557,lost,6 wickets,31.000000,lost,1st,v England,Bristol,14-May-19,ODI # 4135,Pakistan,7
1312,996,won,6 wickets,31.000000,won,2nd,v Pakistan,Bristol,14-May-19,ODI # 4135,England,1
1313,1094,won,6 wickets,42.000000,lost,2nd,v Ireland,Dublin,15-May-19,ODI # 4136,Bangladesh,25
1314,120,lost,5 wickets,7.000000,lost,1st,v Bangladesh,Dublin (Malahide),17-May-19,ODI # 4137,WestIndies,4
1315,1095,won,5 wickets,7.000000,won,2nd,v West Indies,Dublin (Malahide),17-May-19,ODI # 4137,Bangladesh,25
1316,558,lost,3 wickets,3.000000,lost,1st,v England,Nottingham,17-May-19,ODI # 4138,Pakistan,7
1317,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,3 wickets,51.409241,won,2nd,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,aban,3 wickets,51.409241,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,aban,3 wickets,51.409241,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,aban,3 wickets,51.409241,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [40]:
df.isna().sum()

sl_no         0
Result        0
Margin        0
BR            0
Toss          0
Bat           0
Opposition    0
Ground        0
Start Date    0
Match_ID      0
Country       0
Country_ID    0
dtype: int64

In [41]:
df.isna().sum().sum()

0

In [21]:
df.to_csv('ODI_Match_Results_cleaned.csv')

In [33]:
df_cleaned = pd.read_csv('ODI_Match_Results_cleaned.csv')

In [23]:
df = pd.read_csv('ODI_Match_Results.csv')

In [45]:
df.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,418,won,85 runs,NaN,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,692,lost,85 runs,NaN,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,419,lost,10 runs,NaN,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,693,won,10 runs,NaN,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,121,lost,107 runs,NaN,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [47]:
df.tail()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
1317,997,won,3 wickets,3.0,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,282,aban,NaN,NaN,NaN,NaN,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1322,NaN,NaN,NaN,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,559,NaN,NaN,NaN,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,998,NaN,NaN,NaN,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [34]:
df_cleaned.head()

,Unnamed: 0,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [49]:
df_cleaned.isna().sum().sum()

0

In [30]:
df_cleaned.isna().sum().mean()

67.0

In [51]:
df_cleaned.tail()

,Unnamed: 0,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
1317,1317,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,1318,282,aban,3 wickets,51.409241,won,2nd,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1319,1322,aban,3 wickets,51.409241,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,1320,559,aban,3 wickets,51.409241,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,1321,998,aban,3 wickets,51.409241,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [7]:
df_cleaned

,Unnamed: 0,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8
5,5,1096,won,107 runs,51.409241,won,1st,v Sri Lanka,Melbourne,11-Jan-13,ODI # 3317,Australia,2
6,6,694,lost,9 runs,51.409241,lost,2nd,v England,Rajkot,11-Jan-13,ODI # 3318,India,6
7,7,852,won,9 runs,51.409241,won,1st,v India,Rajkot,11-Jan-13,ODI # 3318,England,1
8,8,122,won,8 wickets,59.000000,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8
9,9,1097,lost,8 wickets,59.000000,lost,1st,v Sri Lanka,Adelaide,13-Jan-13,ODI # 3319,Australia,2
10,10,695,won,127 runs,51.409241,won,1st,v England,Kochi,15-Jan-13,ODI # 3320,India,6
11,11,853,lost,127 runs,51.409241,lost,2nd,v India,Kochi,15-Jan-13,ODI # 3320,England,1
12,12,123,won,4 wickets,180.000000,lost,2nd,v Australia,Brisbane,18-Jan-13,ODI # 3321,SriLanka,8
13,13,1098,lost,4 wickets,180.000000,won,1st,v Sri Lanka,Brisbane,18-Jan-13,ODI # 3321,Australia,2
14,14,696,won,7 wickets,131.000000,won,2nd,v England,Ranchi,19-Jan-13,ODI # 3322,India,6
15,15,854,lost,7 wickets,131.000000,lost,1st,v India,Ranchi,19-Jan-13,ODI # 3322,England,1
16,16,283,lost,1 wickets,26.000000,lost,1st,v New Zealand,Paarl,19-Jan-13,ODI # 3323,SouthAfrica,3
17,17,560,won,1 wickets,26.000000,won,2nd,v South Africa,Paarl,19-Jan-13,ODI # 3323,NewZealand,5
18,18,124,n/r,1 wickets,51.409241,lost,2nd,v Australia,Sydney,20-Jan-13,ODI # 3324,SriLanka,8
19,19,1099,n/r,1 wickets,51.409241,won,1st,v Sri Lanka,Sydney,20-Jan-13,ODI # 3324,Australia,2
20,20,284,lost,27 runs,51.409241,won,2nd,v New Zealand,Kimberley,22-Jan-13,ODI # 3325,SouthAfrica,3
21,21,561,won,27 runs,51.409241,lost,1st,v South Africa,Kimberley,22-Jan-13,ODI # 3325,NewZealand,5
22,22,125,lost,32 runs,51.409241,won,2nd,v Australia,Hobart,23-Jan-13,ODI # 3326,SriLanka,8
23,23,1100,won,32 runs,51.409241,lost,1st,v Sri Lanka,Hobart,23-Jan-13,ODI # 3326,Australia,2
24,24,697,won,5 wickets,15.000000,won,2nd,v England,Mohali,23-Jan-13,ODI # 3327,India,6
25,25,855,lost,5 wickets,15.000000,lost,1st,v India,Mohali,23-Jan-13,ODI # 3327,England,1
26,26,285,won,1 wickets,0.000000,lost,2nd,v New Zealand,Potchefstroom,25-Jan-13,ODI # 3328,SouthAfrica,3
27,27,562,lost,1 wickets,0.000000,won,1st,v South Africa,Potchefstroom,25-Jan-13,ODI # 3328,NewZealand,5
28,28,698,lost,7 wickets,16.000000,lost,1st,v England,Dharamsala,27-Jan-13,ODI # 3329,India,6
29,29,856,won,7 wickets,16.000000,won,2nd,v India,Dharamsala,27-Jan-13,ODI # 3329,England,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292,1292,1228,won,80 runs,51.409241,won,1st,v Pakistan,Abu Dhabi,27-Mar-19,ODI # 4118,Australia,2
1293,1293,553,lost,6 runs,51.409241,won,2nd,v Australia,Dubai (DSC),29-Mar-19,ODI # 4119,Pakistan,7
1294,1294,1229,won,6 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),29-Mar-19,ODI # 4119,Australia,2
1295,1295,554,lost,20 runs,51.409241,won,2nd,v Australia,Dubai (DSC),31-Mar-19,ODI # 4120,Pakistan,7
1296,1296,1230,won,20 runs,51.409241,lost,1st,v Pakistan,Dubai (DSC),31-Mar-19,ODI # 4120,Australia,2
1297,1297,993,won,4 wickets,18.000000,won,2nd,v Ireland,Dublin (Malahide),3-May-19,ODI # 4127,England,1
1298,1298,116,won,196 runs,51.409241,lost,1st,v Ireland,Dublin,5-May-19,ODI # 4128,WestIndies,4
1299,1299,117,lost,8 wickets,30.000000,won,1st,v Bangladesh,Dublin,7-May-19,ODI # 4129,WestIndies,4
1300,1300,1091,won,8 wickets,30.000000,lost,2nd,v West Indies,Dublin,7-May-19,ODI # 4129,Bangladesh,25
1301,1301,1320,aban,8 wickets,51.409241,lost,2nd,v Scotland,Edinburgh,8-May-19,ODI # 4129a,Afghanistan,40
1302,1302,555,n/r,8 wickets,51.409241,lost,1st,v England,The Oval,8-May-19,ODI # 4130,Pakistan,7
1303,1303,994,n/r,8 wickets,51.409241,won,2nd,v Pakistan,The Oval,8-May-19,ODI # 4130,England,1
1304,1304,1092,aban,8 wickets,51.409241,won,2nd,v Ireland,Dublin (Malahide),9-May-19,ODI # 4130a,Bangladesh,25
1305,1305,1321,won,2 runs,51.409241,lost,2nd,v Scotland,Edinburgh,10-May-19,ODI # 4131,Afghanistan,40
1306,1306,118,won,5 wickets,13.000000,lost,2nd,v Ireland,Dublin (Malahide),11-May-19,ODI # 4132,WestIndies,4
1307,1307,556,lost,12 runs,51.409241,won,2nd,v England,Southampton,11-May-19,ODI # 4133,Pakistan,7
1308,1308,995,won,12 runs,51.409241,lost,1st,v Pakistan,Southampton,11-May-19,ODI # 4133,England,1
1309,1309,119,lost,5 wickets,16.000000,won,1st,v Bangladesh,Dublin (Malahide),13-May-19,ODI # 4134,WestIndies,4
1310,1310,1093,won,5 wickets,16.000000,lost,2nd,v West Indies,Dublin (Malahide),13-May-19,ODI # 4134,Bangladesh,25
1311,1311,557,lost,6 wickets,31.000000,lost,1st,v England,Bristol,14-May-19,ODI # 4135,Pakistan,7
1312,1312,996,won,6 wickets,31.000000,won,2nd,v Pakistan,Bristol,14-May-19,ODI # 4135,England,1
1313,1313,1094,won,6 wickets,42.000000,lost,2nd,v Ireland,Dublin,15-May-19,ODI # 4136,Bangladesh,25
1314,1314,120,lost,5 wickets,7.000000,lost,1st,v Bangladesh,Dublin (Malahide),17-May-19,ODI # 4137,WestIndies,4
1315,1315,1095,won,5 wickets,7.000000,won,2nd,v West Indies,Dublin (Malahide),17-May-19,ODI # 4137,Bangladesh,25
1316,1316,558,lost,3 wickets,3.000000,lost,1st,v England,Nottingham,17-May-19,ODI # 4138,Pakistan,7
1317,1317,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,1318,282,aban,3 wickets,51.409241,won,2nd,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1319,1322,aban,3 wickets,51.409241,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,1320,559,aban,3 wickets,51.409241,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,1321,998,aban,3 wickets,51.409241,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [15]:
from sklearn import preprocessing

In [35]:
x_array = np.array(df_cleaned['BR'])

In [36]:
x_array

array([51.40924092, 51.40924092, 51.40924092, ..., 51.40924092,
       51.40924092, 51.40924092])

In [37]:
normalized_X = preprocessing.normalize([x_array])

In [38]:
normalized_X

array([[0.02215158, 0.02215158, 0.02215158, ..., 0.02215158, 0.02215158,
        0.02215158]])

In [39]:
df_cleaned.head()

,Unnamed: 0,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [40]:
df_cleaned.to_csv('ODI_Results_normalized.csv')

In [41]:
df_norm = pd.read_csv('ODI_Results_normalized.csv')

In [42]:
df_norm.head()

,Unnamed: 0,Unnamed: 0.1,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,0,0,418,won,85 runs,51.409241,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,1,1,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,2,2,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,3,3,693,won,10 runs,51.409241,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,4,4,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [43]:
a = np.array(df_norm['BR'])

In [44]:
a

array([51.40924092, 51.40924092, 51.40924092, ..., 51.40924092,
       51.40924092, 51.40924092])

In [49]:
    for j in normalized_X:
        df_norm['BR'] = j

In [55]:
df_norm.head()

,Unnamed: 0,Unnamed: 0.1,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,0,0,418,won,85 runs,0.022152,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,1,1,692,lost,85 runs,0.022152,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,2,2,419,lost,10 runs,0.022152,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,3,3,693,won,10 runs,0.022152,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,4,4,121,lost,107 runs,0.022152,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8

In [52]:
import matplotlib.pyplot as plt


N = 10
bat_2 = (20, 35, 30, 35, 27)
bat_1 = (25, 32, 34, 20, 25)
bat_2Std = (2, 3, 4, 1, 2)
bat_1Std = (3, 5, 2, 3, 3)
ind = np.arange(N)    # the x locations for the groups
width = 0.35       # the width of the bars: can also be len(x) sequence

p1 = plt.bar(ind, bat_2, width, yerr=bat_2Std)
p2 = plt.bar(ind, bat_1, width,
             bottom=bat_1Means, yerr=bat_1Std)

plt.ylabel('Scores')
plt.title('Scores by group and gender')
plt.xticks(ind, ('G1', 'G2', 'G3', 'G4', 'G5'))
plt.yticks(np.arange(0, 81, 10))
plt.legend((p1[0], p2[0]), ('Men', 'Women'))

plt.show()

KeyError: 'Won'

In [56]:
df_norm

,Unnamed: 0,Unnamed: 0.1,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,0,0,418,won,85 runs,0.022152,lost,1st,v India,Kolkata,3-Jan-13,ODI # 3315,Pakistan,7
1,1,1,692,lost,85 runs,0.022152,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
2,2,2,419,lost,10 runs,0.022152,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
3,3,3,693,won,10 runs,0.022152,won,1st,v Pakistan,Delhi,6-Jan-13,ODI # 3316,India,6
4,4,4,121,lost,107 runs,0.022152,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8
5,5,5,1096,won,107 runs,0.022152,won,1st,v Sri Lanka,Melbourne,11-Jan-13,ODI # 3317,Australia,2
6,6,6,694,lost,9 runs,0.022152,lost,2nd,v England,Rajkot,11-Jan-13,ODI # 3318,India,6
7,7,7,852,won,9 runs,0.022152,won,1st,v India,Rajkot,11-Jan-13,ODI # 3318,England,1
8,8,8,122,won,8 wickets,0.025422,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8
9,9,9,1097,lost,8 wickets,0.025422,lost,1st,v Sri Lanka,Adelaide,13-Jan-13,ODI # 3319,Australia,2
10,10,10,695,won,127 runs,0.022152,won,1st,v England,Kochi,15-Jan-13,ODI # 3320,India,6
11,11,11,853,lost,127 runs,0.022152,lost,2nd,v India,Kochi,15-Jan-13,ODI # 3320,England,1
12,12,12,123,won,4 wickets,0.077560,lost,2nd,v Australia,Brisbane,18-Jan-13,ODI # 3321,SriLanka,8
13,13,13,1098,lost,4 wickets,0.077560,won,1st,v Sri Lanka,Brisbane,18-Jan-13,ODI # 3321,Australia,2
14,14,14,696,won,7 wickets,0.056446,won,2nd,v England,Ranchi,19-Jan-13,ODI # 3322,India,6
15,15,15,854,lost,7 wickets,0.056446,lost,1st,v India,Ranchi,19-Jan-13,ODI # 3322,England,1
16,16,16,283,lost,1 wickets,0.011203,lost,1st,v New Zealand,Paarl,19-Jan-13,ODI # 3323,SouthAfrica,3
17,17,17,560,won,1 wickets,0.011203,won,2nd,v South Africa,Paarl,19-Jan-13,ODI # 3323,NewZealand,5
18,18,18,124,n/r,1 wickets,0.022152,lost,2nd,v Australia,Sydney,20-Jan-13,ODI # 3324,SriLanka,8
19,19,19,1099,n/r,1 wickets,0.022152,won,1st,v Sri Lanka,Sydney,20-Jan-13,ODI # 3324,Australia,2
20,20,20,284,lost,27 runs,0.022152,won,2nd,v New Zealand,Kimberley,22-Jan-13,ODI # 3325,SouthAfrica,3
21,21,21,561,won,27 runs,0.022152,lost,1st,v South Africa,Kimberley,22-Jan-13,ODI # 3325,NewZealand,5
22,22,22,125,lost,32 runs,0.022152,won,2nd,v Australia,Hobart,23-Jan-13,ODI # 3326,SriLanka,8
23,23,23,1100,won,32 runs,0.022152,lost,1st,v Sri Lanka,Hobart,23-Jan-13,ODI # 3326,Australia,2
24,24,24,697,won,5 wickets,0.006463,won,2nd,v England,Mohali,23-Jan-13,ODI # 3327,India,6
25,25,25,855,lost,5 wickets,0.006463,lost,1st,v India,Mohali,23-Jan-13,ODI # 3327,England,1
26,26,26,285,won,1 wickets,0.000000,lost,2nd,v New Zealand,Potchefstroom,25-Jan-13,ODI # 3328,SouthAfrica,3
27,27,27,562,lost,1 wickets,0.000000,won,1st,v South Africa,Potchefstroom,25-Jan-13,ODI # 3328,NewZealand,5
28,28,28,698,lost,7 wickets,0.006894,lost,1st,v England,Dharamsala,27-Jan-13,ODI # 3329,India,6
29,29,29,856,won,7 wickets,0.006894,won,2nd,v India,Dharamsala,27-Jan-13,ODI # 3329,England,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292,1292,1292,1228,won,80 runs,0.022152,won,1st,v Pakistan,Abu Dhabi,27-Mar-19,ODI # 4118,Australia,2
1293,1293,1293,553,lost,6 runs,0.022152,won,2nd,v Australia,Dubai (DSC),29-Mar-19,ODI # 4119,Pakistan,7
1294,1294,1294,1229,won,6 runs,0.022152,lost,1st,v Pakistan,Dubai (DSC),29-Mar-19,ODI # 4119,Australia,2
1295,1295,1295,554,lost,20 runs,0.022152,won,2nd,v Australia,Dubai (DSC),31-Mar-19,ODI # 4120,Pakistan,7
1296,1296,1296,1230,won,20 runs,0.022152,lost,1st,v Pakistan,Dubai (DSC),31-Mar-19,ODI # 4120,Australia,2
1297,1297,1297,993,won,4 wickets,0.007756,won,2nd,v Ireland,Dublin (Malahide),3-May-19,ODI # 4127,England,1
1298,1298,1298,116,won,196 runs,0.022152,lost,1st,v Ireland,Dublin,5-May-19,ODI # 4128,WestIndies,4
1299,1299,1299,117,lost,8 wickets,0.012927,won,1st,v Bangladesh,Dublin,7-May-19,ODI # 4129,WestIndies,4
1300,1300,1300,1091,won,8 wickets,0.012927,lost,2nd,v West Indies,Dublin,7-May-19,ODI # 4129,Bangladesh,25
1301,1301,1301,1320,aban,8 wickets,0.022152,lost,2nd,v Scotland,Edinburgh,8-May-19,ODI # 4129a,Afghanistan,40
1302,1302,1302,555,n/r,8 wickets,0.022152,lost,1st,v England,The Oval,8-May-19,ODI # 4130,Pakistan,7
1303,1303,1303,994,n/r,8 wickets,0.022152,won,2nd,v Pakistan,The Oval,8-May-19,ODI # 4130,England,1
1304,1304,1304,1092,aban,8 wickets,0.022152,won,2nd,v Ireland,Dublin (Malahide),9-May-19,ODI # 4130a,Bangladesh,25
1305,1305,1305,1321,won,2 runs,0.022152,lost,2nd,v Scotland,Edinburgh,10-May-19,ODI # 4131,Afghanistan,40
1306,1306,1306,118,won,5 wickets,0.005602,lost,2nd,v Ireland,Dublin (Malahide),11-May-19,ODI # 4132,WestIndies,4
1307,1307,1307,556,lost,12 runs,0.022152,won,2nd,v England,Southampton,11-May-19,ODI # 4133,Pakistan,7
1308,1308,1308,995,won,12 runs,0.022152,lost,1st,v Pakistan,Southampton,11-May-19,ODI # 4133,England,1
1309,1309,1309,119,lost,5 wickets,0.006894,won,1st,v Bangladesh,Dublin (Malahide),13-May-19,ODI # 4134,WestIndies,4
1310,1310,1310,1093,won,5 wickets,0.006894,lost,2nd,v West Indies,Dublin (Malahide),13-May-19,ODI # 4134,Bangladesh,25
1311,1311,1311,557,lost,6 wickets,0.013357,lost,1st,v England,Bristol,14-May-19,ODI # 4135,Pakistan,7
1312,1312,1312,996,won,6 wickets,0.013357,won,2nd,v Pakistan,Bristol,14-May-19,ODI # 4135,England,1
1313,1313,1313,1094,won,6 wickets,0.018097,lost,2nd,v Ireland,Dublin,15-May-19,ODI # 4136,Bangladesh,25
1314,1314,1314,120,lost,5 wickets,0.003016,lost,1st,v Bangladesh,Dublin (Malahide),17-May-19,ODI # 4137,WestIndies,4
1315,1315,1315,1095,won,5 wickets,0.003016,won,2nd,v West Indies,Dublin (Malahide),17-May-19,ODI # 4137,Bangladesh,25
1316,1316,1316,558,lost,3 wickets,0.001293,lost,1st,v England,Nottingham,17-May-19,ODI # 4138,Pakistan,7
1317,1317,1317,997,won,3 wickets,0.001293,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1
1318,1318,1318,282,aban,3 wickets,0.022152,won,2nd,v Scotland,Edinburgh,18-May-19,ODI # 4138a,SriLanka,8
1319,1319,1319,1322,aban,3 wickets,0.022152,won,2nd,v Ireland,Belfast,19-May-19,ODI # 4139,Afghanistan,40
1320,1320,1320,559,aban,3 wickets,0.022152,lost,2nd,v England,Leeds,19-May-19,ODI # 4140,Pakistan,7
1321,1321,1321,998,aban,3 wickets,0.022152,won,1st,v Pakistan,Leeds,19-May-19,ODI # 4140,England,1

In [119]:
import csv
with open('ODI_Results_normalized.csv','r') as bat2in:
    with open('batting_2.csv','w') as batt_2:
            writer = csv.writer(batt_2)
            for row in csv.reader(bat2in):
                if row[7] == '2nd' and row[3] == 'won':
                    writer.writerow(row)

In [173]:
d = pd.read_csv('batting_2.csv')

In [138]:
d.shape

(332, 12)

In [174]:
d.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,122,won,8 wickets,59.0,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8
1,123,won,4 wickets,180.0,lost,2nd,v Australia,Brisbane,18-Jan-13,ODI # 3321,SriLanka,8
2,696,won,7 wickets,131.0,won,2nd,v England,Ranchi,19-Jan-13,ODI # 3322,India,6
3,560,won,1 wickets,26.0,won,2nd,v South Africa,Paarl,19-Jan-13,ODI # 3323,NewZealand,5
4,697,won,5 wickets,15.0,won,2nd,v England,Mohali,23-Jan-13,ODI # 3327,India,6

In [131]:
with open('ODI_Results_normalized.csv','r') as bat2in:
    with open('batting_1.csv','w') as batt_2:
            writer = csv.writer(batt_2)
            for row in csv.reader(bat2in):
                if row[7] == '1st' and row[3] == 'won':
                    writer.writerow(row)

In [135]:
countries = set(df['Country'])

In [136]:
countries

{'Afghanistan',
 'Australia',
 'Bangladesh',
 'England',
 'India',
 'NewZealand',
 'Pakistan',
 'SouthAfrica',
 'SriLanka',
 'WestIndies'}

In [181]:
with open("batting_2.csv",'r') as f:
    d1 = csv.reader(f)
    with open("batting_2_won_lost.csv",'r') as l:
        g1 = csv.reader(l)
        for i in countries:
            flag1 = 0
            flag2 = 0
            for j in d1:
                if j[10] == i:
                    flag1 = flag1 + 1
            for k in g1:
                if k[10] == i:
                    flag2 = flag2 + 1
            m = (flag1/flag2) *100
            h.append(m)

ZeroDivisionError: division by zero

In [161]:
with open('ODI_Results_normalized.csv','r') as bat2in:
    with open('batting_2_won_lost.csv','w') as batt_2:
            writer = csv.writer(batt_2)
            for row in csv.reader(bat2in):
                if row[7] == '2nd':
                    writer.writerow(row)

PermissionError: [Errno 13] Permission denied: 'batting_2_won_lost.csv'

In [159]:
g = pd.read_csv('batting_2_won_lost.csv')

In [146]:
g.shape

(644, 12)

In [147]:
g.head()

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,692,lost,85 runs,51.409241,won,2nd,v Pakistan,Kolkata,3-Jan-13,ODI # 3315,India,6
1,419,lost,10 runs,51.409241,lost,2nd,v India,Delhi,6-Jan-13,ODI # 3316,Pakistan,7
2,121,lost,107 runs,51.409241,lost,2nd,v Australia,Melbourne,11-Jan-13,ODI # 3317,SriLanka,8
3,694,lost,9 runs,51.409241,lost,2nd,v England,Rajkot,11-Jan-13,ODI # 3318,India,6
4,122,won,8 wickets,59.000000,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8

In [152]:
h = list()

In [154]:
h

[]

In [172]:
with open("batting_2_won_lost.csv") as f:
    reader = csv.reader(f)
    for row in reader:
        print(row[1])

Result
lost
lost
lost
lost
won
lost
won
won
won
n/r
lost
lost
won
won
won
won
lost
lost
won
lost
won
won
won
won
won
won
won
lost
won
lost
won
won
won
n/r
won
won
won
lost
lost
lost
won
lost
won
lost
won
n/r
won
tied
won
lost
lost
won
won
lost
won
won
lost
lost
lost
lost
won
lost
lost
tied
lost
won
lost
won
won
lost
won
won
lost
won
won
won
lost
n/r
won
lost
won
won
lost
won
won
n/r
lost
won
lost
lost
lost
lost
won
lost
lost
n/r
lost
won
lost
won
won
lost
won
lost
won
lost
lost
n/r
lost
won
lost
won
won
won
lost
lost
lost
won
won
lost
won
lost
lost
tied
lost
won
lost
lost
lost
won
won
lost
won
lost
won
lost
lost
won
won
lost
won
won
lost
won
won
won
lost
lost
won
lost
won
won
lost
n/r
lost
lost
lost
won
won
won
lost
won
lost
lost
won
lost
won
won
lost
won
lost
won
lost
lost
won
lost
lost
lost
won
lost
n/r
lost
won
won
lost
lost
won
won
lost
won
won
lost
won
won
won
won
lost
won
won
won
won
lost
lost
lost
lost
lost
won
won
lost
won
won
lost
n/r
won
lost
won
won
won
lost
won
lost
won
n/r
lost
lost
won
won
lost
lost
lost
lost
lost
won
lost
won
lost
aban
aban
won
lost
won
lost
lost
won
won
won
lost
won
won
lost
won
lost
lost
won
won
won
won
won
won
won
won
lost
won
lost
won
lost
won
lost
won
won
n/r
won
lost
lost
won
won
lost
won
won
lost
won
won
won
won
won
lost
won
lost
won
lost
won
lost
lost
lost
lost
won
won
lost
won
lost
lost
lost
won
lost
lost
won
won
won
won
lost
won
lost
won
won
won
won
n/r
lost
lost
lost
won
won
won
won
lost
won
lost
won
lost
lost
won
won
lost
won
won
won
won
won
lost
won
lost
won
won
won
lost
n/r
tied
won
won
lost
n/r
lost
won
lost
lost
won
lost
won
won
won
lost
won
won
won
won
lost
won
won
lost
won
lost
lost
lost
lost
won
lost
won
lost
won
lost
won
lost
won
lost
lost
won
lost
tied
n/r
lost
lost
won
lost
lost
lost
lost
lost
won
lost
won
won
won
lost
lost
lost
lost
won
lost
lost
won
lost
lost
lost
won
lost
lost
lost
won
lost
won
won
lost
won
lost
n/r
lost
won
lost
won
won
won
won
won
lost
lost
won
won
n/r
lost
lost
n/r
lost
won
won
won
lost
won
won
won
won
won
won
lost
n/r
lost
lost
won
lost
won
won
won
won
won
lost
won
aban
lost
won
lost
n/r
won
lost
won
lost
won
won
lost
won
lost
lost
won
won
won
lost
won
won
lost
lost
won
lost
won
won
lost
lost
lost
won
lost
won
won
won
lost
lost
won
lost
lost
won
won
won
lost
lost
won
won
lost
won
lost
won
lost
won
won
won
won
lost
lost
won
lost
won
won
won
won
won
won
won
lost
won
lost
lost
won
won
won
lost
won
won
won
lost
lost
lost
won
won
lost
lost
lost
won
lost
won
lost
won
lost
won
won
won
lost
tied
lost
won
won
won
n/r
lost
won
won
won
lost
tied
won
won
lost
lost
won
won
lost
lost
won
lost
n/r
won
won
won
lost
lost
lost
lost
won
won
won
won
won
won
lost
won
won
won
won
lost
won
won
lost
won
lost
n/r
n/r
lost
won
won
won
won
lost
lost
lost
won
lost
lost
won
won
won
won
lost
lost
lost
won
won
aban
n/r
aban
won
won
lost
won
won
won
won
won
aban
aban
aban

In [165]:
d

,sl_no,Result,Margin,BR,Toss,Bat,Opposition,Ground,Start Date,Match_ID,Country,Country_ID
0,122,won,8 wickets,59.000000,won,2nd,v Australia,Adelaide,13-Jan-13,ODI # 3319,SriLanka,8
1,123,won,4 wickets,180.000000,lost,2nd,v Australia,Brisbane,18-Jan-13,ODI # 3321,SriLanka,8
2,696,won,7 wickets,131.000000,won,2nd,v England,Ranchi,19-Jan-13,ODI # 3322,India,6
3,560,won,1 wickets,26.000000,won,2nd,v South Africa,Paarl,19-Jan-13,ODI # 3323,NewZealand,5
4,697,won,5 wickets,15.000000,won,2nd,v England,Mohali,23-Jan-13,ODI # 3327,India,6
5,285,won,1 wickets,0.000000,lost,2nd,v New Zealand,Potchefstroom,25-Jan-13,ODI # 3328,SouthAfrica,3
6,856,won,7 wickets,16.000000,won,2nd,v India,Dharamsala,27-Jan-13,ODI # 3329,England,1
7,1101,won,9 wickets,244.000000,lost,2nd,v West Indies,Perth,1-Feb-13,ODI # 3330,Australia,2
8,1104,won,5 wickets,31.000000,lost,2nd,v West Indies,Sydney,8-Feb-13,ODI # 3333,Australia,2
9,563,won,3 wickets,7.000000,won,2nd,v England,Hamilton,17-Feb-13,ODI # 3335,NewZealand,5
10,858,won,8 wickets,14.000000,won,2nd,v New Zealand,Napier,20-Feb-13,ODI # 3336,England,1
11,859,won,5 wickets,75.000000,won,2nd,v New Zealand,Auckland,23-Feb-13,ODI # 3338,England,1
12,7,won,7 wickets,6.000000,lost,2nd,v Zimbabwe,St George's,24-Feb-13,ODI # 3339,WestIndies,4
13,8,won,5 wickets,22.000000,lost,2nd,v Zimbabwe,St George's,26-Feb-13,ODI # 3340,WestIndies,4
14,1231,won,7 wickets,97.000000,lost,2nd,v Scotland,Sharjah,6-Mar-13,ODI # 3341,Afghanistan,40
15,1232,won,5 wickets,8.000000,won,2nd,v Scotland,Sharjah,8-Mar-13,ODI # 3342,Afghanistan,40
16,421,won,6 wickets,28.000000,lost,2nd,v South Africa,Centurion,15-Mar-13,ODI # 3346,Pakistan,7
17,423,won,3 wickets,8.000000,lost,2nd,v South Africa,Durban,21-Mar-13,ODI # 3348,Pakistan,7
18,126,won,8 wickets,32.000000,won,2nd,v Bangladesh,Hambantota,23-Mar-13,ODI # 3349,SriLanka,8
19,290,won,6 wickets,36.000000,lost,2nd,v Pakistan,Benoni,24-Mar-13,ODI # 3350,SouthAfrica,3
20,1001,won,3 wickets,6.000000,lost,2nd,v Sri Lanka,Pallekele,28-Mar-13,ODI # 3352,Bangladesh,25
21,428,won,2 wickets,8.000000,won,2nd,v Ireland,Dublin,26-May-13,ODI # 3358,Pakistan,7
22,566,won,5 wickets,19.000000,won,2nd,v England,Lord's,31-May-13,ODI # 3360,NewZealand,5
23,9,won,2 wickets,56.000000,won,2nd,v Pakistan,The Oval,7-Jun-13,ODI # 3364,WestIndies,4
24,569,won,1 wickets,81.000000,lost,2nd,v Sri Lanka,Cardiff,9-Jun-13,ODI # 3366,NewZealand,5
25,700,won,8 wickets,65.000000,won,2nd,v West Indies,The Oval,11-Jun-13,ODI # 3368,India,6
26,130,won,7 wickets,17.000000,won,2nd,v England,The Oval,13-Jun-13,ODI # 3370,SriLanka,8
27,701,won,8 wickets,17.000000,won,2nd,v Pakistan,Birmingham,15-Jun-13,ODI # 3372,India,6
28,866,won,7 wickets,75.000000,won,2nd,v South Africa,The Oval,19-Jun-13,ODI # 3375,England,1
29,702,won,8 wickets,90.000000,won,2nd,v Sri Lanka,Cardiff,20-Jun-13,ODI # 3376,India,6
...,...,...,...,...,...,...,...,...,...,...,...,...
302,841,won,7 wickets,4.000000,won,2nd,v Australia,Melbourne,18-Jan-19,ODI # 4079,India,6
303,545,won,5 wickets,5.000000,lost,2nd,v South Africa,Port Elizabeth,19-Jan-19,ODI # 4080,Pakistan,7
304,409,won,5 wickets,48.000000,won,2nd,v Pakistan,Durban,22-Jan-19,ODI # 4081,SouthAfrica,3
305,842,won,8 wickets,85.000000,lost,2nd,v New Zealand,Napier,23-Jan-19,ODI # 4082,India,6
306,410,won,13 runs,51.409241,lost,2nd,v Pakistan,Centurion,25-Jan-19,ODI # 4084,SouthAfrica,3
307,548,won,8 wickets,111.000000,won,2nd,v South Africa,Johannesburg,27-Jan-19,ODI # 4087,Pakistan,7
308,844,won,7 wickets,42.000000,lost,2nd,v New Zealand,Mount Maunganui,28-Jan-19,ODI # 4088,India,6
309,412,won,7 wickets,60.000000,won,2nd,v Pakistan,Cape Town,30-Jan-19,ODI # 4090,SouthAfrica,3
310,687,won,8 wickets,212.000000,won,2nd,v India,Hamilton,31-Jan-19,ODI # 4091,NewZealand,5
311,689,won,8 wickets,33.000000,lost,2nd,v Bangladesh,Napier,13-Feb-19,ODI # 4093,NewZealand,5
312,690,won,8 wickets,83.000000,won,2nd,v Bangladesh,Christchurch,16-Feb-19,ODI # 4094,NewZealand,5
313,988,won,6 wickets,8.000000,lost,2nd,v West Indies,Bridgetown,20-Feb-19,ODI # 4096,England,1
314,1315,won,5 wickets,49.000000,lost,2nd,v Ireland,Dehradun,28-Feb-19,ODI # 4100,Afghanistan,40
315,847,won,6 wickets,10.000000,lost,2nd,v Australia,Hyderabad (Deccan),2-Mar-19,ODI # 4102,India,6
316,115,won,7 wickets,227.000000,won,2nd,v England,Gros Islet,2-Mar-19,ODI # 4103,WestIndies,4
317,413,won,8 wickets,67.000000,won,2nd,v Sri Lanka,Johannesburg,3-Mar-19,ODI # 4104,SouthAfrica,3
318,1224,won,4 wickets,13.000000,lost,2nd,v India,Mohali,10-Mar-19,ODI # 4111,Australia,2
319,416,won,6 wickets,103.000000,won,2nd,v Sri Lanka,Port Elizabeth,13-Mar-19,ODI # 4114,SouthAfrica,3
320,417,won,41 runs,51.409241,lost,2nd,v Sri Lanka,Cape Town,16-Mar-19,ODI # 4115,SouthAfrica,3
321,1226,won,8 wickets,6.000000,lost,2nd,v Pakistan,Sharjah,22-Mar-19,ODI # 4116,Australia,2
322,1227,won,8 wickets,13.000000,lost,2nd,v Pakistan,Sharjah,24-Mar-19,ODI # 4117,Australia,2
323,993,won,4 wickets,18.000000,won,2nd,v Ireland,Dublin (Malahide),3-May-19,ODI # 4127,England,1
324,1091,won,8 wickets,30.000000,lost,2nd,v West Indies,Dublin,7-May-19,ODI # 4129,Bangladesh,25
325,1321,won,2 runs,51.409241,lost,2nd,v Scotland,Edinburgh,10-May-19,ODI # 4131,Afghanistan,40
326,118,won,5 wickets,13.000000,lost,2nd,v Ireland,Dublin (Malahide),11-May-19,ODI # 4132,WestIndies,4
327,1093,won,5 wickets,16.000000,lost,2nd,v West Indies,Dublin (Malahide),13-May-19,ODI # 4134,Bangladesh,25
328,996,won,6 wickets,31.000000,won,2nd,v Pakistan,Bristol,14-May-19,ODI # 4135,England,1
329,1094,won,6 wickets,42.000000,lost,2nd,v Ireland,Dublin,15-May-19,ODI # 4136,Bangladesh,25
330,1095,won,5 wickets,7.000000,won,2nd,v West Indies,Dublin (Malahide),17-May-19,ODI # 4137,Bangladesh,25
331,997,won,3 wickets,3.000000,won,2nd,v Pakistan,Nottingham,17-May-19,ODI # 4138,England,1